language: node_js
node_js:
  - 12.6
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm i react-mdl --save
  - npm i react-router-dom --save
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master